server:
    port: 8899
spring:
    application:
        name: SpringBootMVCProjectFinal
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        password: manager
        url: jdbc:oracle:thin:@//localhost:1521/xe
        username: System
    jpa:
        database-platform: org.hibernate.dialect.OracleDialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: true